"""Text-only local provenance visibility research candidate."""

from .agent import (
    MediaKind,
    ProvenanceVisibilityAgent,
    ProvenanceVisibilityReport,
    SignalEvidence,
    SignalOutcome,
    SignalType,
    render_markdown,
)
from .repository_scan import (
    FamilyAggregate,
    RepositoryFileResult,
    RepositoryScanReport,
    ScanPolicy,
    ScanStatus,
    render_repository_scan_json,
    render_repository_scan_markdown,
    scan_text_repository,
)
from .text_reveal import (
    CueKind,
    EvidenceFamily,
    EvidenceRecord,
    MontagePanel,
    PeriodicCue,
    RawTextProfile,
    TextCue,
    TextRevealReport,
    render_text_reveal_markdown,
    reveal_hidden_text_bytes,
    reveal_hidden_text_signal,
)

__all__ = [
    "FamilyAggregate",
    "RepositoryFileResult",
    "RepositoryScanReport",
    "ScanPolicy",
    "ScanStatus",
    "CueKind",
    "EvidenceFamily",
    "EvidenceRecord",
    "MediaKind",
    "MontagePanel",
    "PeriodicCue",
    "ProvenanceVisibilityAgent",
    "ProvenanceVisibilityReport",
    "RawTextProfile",
    "SignalEvidence",
    "SignalOutcome",
    "SignalType",
    "TextCue",
    "TextRevealReport",
    "render_markdown",
    "render_repository_scan_json",
    "render_repository_scan_markdown",
    "render_text_reveal_markdown",
    "reveal_hidden_text_bytes",
    "reveal_hidden_text_signal",
    "scan_text_repository",
]
