"""Work anthropomorphic Siberian-Husky canid research candidate v0.2."""

from .models import (
    BACULUM_10_30_KG_MEAN_CM,
    BACULUM_10_30_KG_SD_CM,
    HUSKY_MALE_MASS_KG,
    HUSKY_MALE_WITHERS_CM,
    REQUIRED_CANINE_MALE_TOPOLOGY,
    UNKNOWN_NOT_ESTABLISHED,
    UNSPECIFIED,
    SyntheticBaculumDesign,
    SyntheticSizeProfile,
    WorkCanidEmbodimentCandidate,
    synthetic_baculum_design,
)
from .physiology import (
    EjaculateFraction,
    EjaculatoryMechanismStage,
    FractionReference,
    MechanismReference,
    PhysiologyReferenceError,
    ReproductivePhysiologyPathway,
    advance_fraction,
    advance_mechanism,
    fraction_reference,
    mechanism_reference,
)
from .validation import ValidationError, deterministic_fingerprint, validate_candidate

__all__ = [
    "BACULUM_10_30_KG_MEAN_CM",
    "BACULUM_10_30_KG_SD_CM",
    "HUSKY_MALE_MASS_KG",
    "HUSKY_MALE_WITHERS_CM",
    "REQUIRED_CANINE_MALE_TOPOLOGY",
    "UNKNOWN_NOT_ESTABLISHED",
    "UNSPECIFIED",
    "SyntheticBaculumDesign",
    "SyntheticSizeProfile",
    "WorkCanidEmbodimentCandidate",
    "synthetic_baculum_design",
    "EjaculateFraction",
    "EjaculatoryMechanismStage",
    "FractionReference",
    "MechanismReference",
    "PhysiologyReferenceError",
    "ReproductivePhysiologyPathway",
    "advance_fraction",
    "advance_mechanism",
    "fraction_reference",
    "mechanism_reference",
    "ValidationError",
    "deterministic_fingerprint",
    "validate_candidate",
]
