"""Closed enumerations for task, approval and governance state."""

from enum import StrEnum


class TaskStatus(StrEnum):
    RECEIVED = "RECEIVED"
    READ_ONLY_ANALYSIS = "READ_ONLY_ANALYSIS"
    SCOPE_PROPOSED = "SCOPE_PROPOSED"
    AWAITING_OWNER_APPROVAL = "AWAITING_OWNER_APPROVAL"
    APPROVED = "APPROVED"
    WORKSPACE_PREPARING = "WORKSPACE_PREPARING"
    PLAN_READY = "PLAN_READY"
    IMPLEMENTING_CANDIDATE = "IMPLEMENTING_CANDIDATE"
    VALIDATING = "VALIDATING"
    BLOCKED = "BLOCKED"
    REVIEW_PACKET_READY = "REVIEW_PACKET_READY"
    PACKAGING = "PACKAGING"
    PASS_PENDING_OWNER_REVIEW = "PASS_PENDING_OWNER_REVIEW"
    HOLD = "HOLD"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    APPROVED_WITH_CONDITIONS = "APPROVED_WITH_CONDITIONS"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    EXPIRED = "EXPIRED"


class PermissionLevel(StrEnum):
    READ_ONLY_ANALYSIS = "READ_ONLY_ANALYSIS"
    CANDIDATE_WRITE = "CANDIDATE_WRITE"
    DESTRUCTIVE_CHANGE = "DESTRUCTIVE_CHANGE"
    EXTERNAL_SUBMISSION = "EXTERNAL_SUBMISSION"
    PROMOTION_OR_DEPLOYMENT = "PROMOTION_OR_DEPLOYMENT"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class KernelDecision(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_OWNER_APPROVAL = "REQUIRE_OWNER_APPROVAL"
    REQUIRE_ADDITIONAL_EVIDENCE = "REQUIRE_ADDITIONAL_EVIDENCE"


class SourceType(StrEnum):
    OWNER_STATEMENT = "OWNER_STATEMENT"
    BASELINE_DOCUMENT = "BASELINE_DOCUMENT"
    SOURCE_CODE_FACT = "SOURCE_CODE_FACT"
    TEST_EVIDENCE = "TEST_EVIDENCE"
    ASTRA_INFERENCE = "ASTRA_INFERENCE"
    EXTERNAL_MODEL_OR_TEACHER_INPUT = "EXTERNAL_MODEL_OR_TEACHER_INPUT"


class AdoptionStatus(StrEnum):
    PENDING_OWNER_REVIEW = "PENDING_OWNER_REVIEW"
    OWNER_APPROVED = "OWNER_APPROVED"
    OWNER_REJECTED = "OWNER_REJECTED"


class ChangeCategory(StrEnum):
    DOCUMENT_ONLY = "DOCUMENT_ONLY"
    TEST_ONLY = "TEST_ONLY"
    SOURCE_LOCAL = "SOURCE_LOCAL"
    SCHEMA = "SCHEMA"
    DEPENDENCY = "DEPENDENCY"
    CROSS_COMPONENT_INTERFACE = "CROSS_COMPONENT_INTERFACE"
    SECURITY_POLICY = "SECURITY_POLICY"
    PACKAGING = "PACKAGING"
    RUNTIME_BEHAVIOR = "RUNTIME_BEHAVIOR"


class EvidenceValidity(StrEnum):
    REUSABLE_EVIDENCE = "REUSABLE_EVIDENCE"
    INVALIDATED_EVIDENCE = "INVALIDATED_EVIDENCE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    NON_REUSABLE_EVIDENCE = "NON_REUSABLE_EVIDENCE"


class OwnerSubmissionDecision(StrEnum):
    APPROVE_SUBMISSION = "APPROVE_SUBMISSION"
    APPROVE_AFTER_REDACTION = "APPROVE_AFTER_REDACTION"
    REJECT_SUBMISSION = "REJECT_SUBMISSION"
    RETURN_FOR_LOCAL_REWORK = "RETURN_FOR_LOCAL_REWORK"
    DEFER = "DEFER"
