from enum import StrEnum


class QAStatus(StrEnum):
    QA_HOLD = "QA_HOLD"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ApprovalStatus(StrEnum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"


class CanonicalEffect(StrEnum):
    NONE = "NONE"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class SubjectivityStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    NOT_ESTABLISHED = "NOT_ESTABLISHED"
    HYPOTHESIS_ONLY = "HYPOTHESIS_ONLY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ForkStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    QA_HOLD = "QA_HOLD"
    MERGE_CANDIDATE = "MERGE_CANDIDATE"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    REVOKED = "REVOKED"


class VerificationResult(StrEnum):
    VALID = "VALID"
    INVALID_HASH = "INVALID_HASH"
    BROKEN_CHAIN = "BROKEN_CHAIN"
    MISSING_PARENT = "MISSING_PARENT"
    MANIFEST_MISMATCH = "MANIFEST_MISMATCH"
    UNAPPROVED_STATE = "UNAPPROVED_STATE"
    UNKNOWN_ARTIFACT = "UNKNOWN_ARTIFACT"
    QA_HOLD = "QA_HOLD"
