import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { buildFactProfile, RULE_PROFILES } from "../src/index.js";

// The facts were selected from HKO's rendered 2033 table, not generated by iztro.
const witness = JSON.parse(await readFile(new URL(
  "../../bazi-capability_v0.1.1/docs/HKO_2033_BOUNDARY_VECTORS.json", import.meta.url), "utf8"));

for (const ruleProfile of Object.keys(RULE_PROFILES)) {
  for (const row of witness.vectors) {
    test(`${ruleProfile} agrees with HKO calendar boundary ${row.gregorian_date}`, () => {
      const solarDate = row.gregorian_date.split("-").map(Number).join("-");
      const [y, m, d] = row.lunar_ymd;
      const base = {
        syntheticFixtureId: "SYNTHETIC-HKO-2033", ruleProfile,
        calendar: {type: "solar", date: solarDate, timeIndex: 6, gender: "女", fixLeap: false, isLeapMonth: false},
      };
      const solar = buildFactProfile(base);
      const lunar = buildFactProfile({...base, calendar: {...base.calendar,
        type: "lunar", date: `${y}-${Math.abs(m)}-${d}`, isLeapMonth: m < 0}});
      assert.equal(lunar.normalizedCalendar.solarDate, solarDate);
      assert.deepEqual(lunar.palaces, solar.palaces);
      assert.equal(solar.coverage.majorStarCount, 14);
      assert.equal(solar.boundaries.CANONICAL_EFFECT, "NONE");
    });
  }
}
