from enum import StrEnum


class QAStatus(StrEnum):
    QA_HOLD = "QA_HOLD"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class EvidenceStatus(StrEnum):
    CONFIRMED_OFFICIAL = "CONFIRMED_OFFICIAL"
    CORROBORATED_MEDIA = "CORROBORATED_MEDIA"
    MEDIA_REPORTED = "MEDIA_REPORTED"
    PROVIDED_SUMMARY_UNVERIFIED = "PROVIDED_SUMMARY_UNVERIFIED"
    NOT_YET_FOUND = "NOT_YET_FOUND"


class Decision(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    STOP_AND_ISOLATE = "STOP_AND_ISOLATE"
    QA_HOLD = "QA_HOLD"


class IncidentPhase(StrEnum):
    DETECTED = "DETECTED"
    STOPPED = "STOPPED"
    ISOLATED = "ISOLATED"
    EVIDENCE_PRESERVED = "EVIDENCE_PRESERVED"
    NCR_OPEN = "NCR_OPEN"
    CAPA_PENDING = "CAPA_PENDING"
    OWNER_RECOVERY_REVIEW = "OWNER_RECOVERY_REVIEW"
